name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.6
      with:
        host: "${{ secrets.SSH_HOST }}"  # Correctly formatted for IPv6
        username: ${{ secrets.SSH_USERNAME }}  # Your server username
        password: ${{ secrets.SSH_PASSWORD }}  # Your server password
        source: "index.php"
        target: "/opt/lampp/htdocs"
        port: 22
